package com.mkreidl.ephemeris

const val ABERRATION = 20.4898 / 3_600 * Math.PI / 180

const val MILLIS_PER_HOUR = 3_600_000L
const val MILLIS_PER_DAY = MILLIS_PER_HOUR * 24
const val MILLIS_PER_YEAR = MILLIS_PER_DAY * 365.25
const val MILLIS_PER_CENTURY = MILLIS_PER_YEAR * 100
const val MILLIS_PER_MILLENNIUM = MILLIS_PER_YEAR * 1_000

const val HOURS_PER_MILLI = 1.0 / MILLIS_PER_HOUR
const val DAYS_PER_MILLI = 1.0 / MILLIS_PER_DAY
const val YEARS_PER_MILLI = 1.0 / MILLIS_PER_YEAR
const val CENTURIES_PER_MILLI = 1.0 / MILLIS_PER_CENTURY
const val MILLENNIA_PER_MILLI = 1.0 / MILLIS_PER_MILLENNIUM

const val SECONDS_PER_DAY = 24 * 3_600
const val DAYS_PER_SECOND = 1.0 / SECONDS_PER_DAY
const val SECONDS_PER_MILLENNIUM = SECONDS_PER_DAY * 365_250L
const val MILLENNIA_PER_SECOND = 1.0 / SECONDS_PER_MILLENNIUM

const val SIDEREAL_PER_SOLAR = 1.00273790935
const val SOLAR_PER_SIDEREAL = 1.0 / SIDEREAL_PER_SOLAR
const val MILLIS_PER_SIDEREAL_HOUR = MILLIS_PER_HOUR * SOLAR_PER_SIDEREAL
const val SIDEREAL_HOURS_PER_MILLI = 1.0 / MILLIS_PER_SIDEREAL_HOUR
const val MILLIS_PER_SIDEREAL_DAY = MILLIS_PER_DAY * SOLAR_PER_SIDEREAL
const val SIDEREAL_DAYS_PER_MILLI = 1.0 / MILLIS_PER_SIDEREAL_DAY

const val SIDEREAL_MILLIS_PER_RADIAN = MILLIS_PER_SIDEREAL_DAY / (2 * Math.PI)

const val J2000_DAY_NUMBER = 2_451_545.0